export const FETCH_ALL_POSTS_STARTED = 'POST/FETCH_ALL_POSTS_STARTED';
export const FETCH_ALL_POSTS_SUCCESS = 'POST/FETCH_ALL_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_FAILURE = 'POST/FETCH_ALL_POSTS_FAILURE';
